name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: add permission
      run: chmod +x gradlew  
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload artifact
    - run: mkdir -p ../../app/release
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: app-release.apk         
        path: ../../app/release
